Milestone 2: User interface
atoledo-ec/tic_tac_toe_ruby pull request #2
Opened 2020-10-21 19:52 UTC by alejandrotoledoweb

## Milestone 2: User interface

For this milestone we have created a main.rb file, and we have a basic flow and logic of the game and how to code it.
The project is incomplete but has the basic class and method we think we need.

2020-10-21 20:41 UTC, krys2fa requested changes
Great job so far @alejandrotoledoweb and @410AngelaVu 👏

Just a few more changes to get this milestone approved. They can be seen below and in the comments:

Status: Changes Required ♻️

**NB**: In this milestone, you are required to only **mock** the basic flow of the game. No game logic (like checking for a winner) is required.

- [x]  [REQUIRED] GitHub Actions as well as running rubocop locally shows a number of offences. Kindly fix this.
Hint: You can use the auto-correct flag to fix most of them (i.e. `rubocop -a`). 

- [x]  [REQUIRED] The game should inform the players if the selected move is a winning move (without computing the winning move).

- [x]  [REQUIRED] The game should inform the players if the selected move is a draw move (without computing the draw).

- [x] [REQUIRED] game tells which player turn it is (without computing who the winner is).

- [x] [REQUIRED] game asks the player to select from available moves.

- [x] [REQUIRED] game informs player if the selected move is invalid (without computing what an invalid move is).

- [x] [REQUIRED] game displays board after the player move (without computing which spots on the board are taken).

- [x]  [REQUIRED] game repeats all actions for the next player's move.

- [x] [REQUIRED] A loop is needed in this game (a `while` loop is recommended but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)).

- [x] [REQUIRED] The loop needs to be terminated at some point (after a winning move or draw to be more specific). 
Hint: This can be done by using a variable to terminate it.

Please request for another review after implementing the changes.

Happy Coding 🖥️ 😃

You can contact me on slack (Chris Amanor) for any clarification.

2020-10-21 20:41 UTC, krys2fa commented on bin/main.rb
> +    gets
- [ ] [REQUIRED] The game breaks after the "coin toss". Please fix this.
Hint: The cause is most likely this `gets` statement on line 143.

2020-10-21 23:34 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. However, it looks like you do not totally understand what this milestone is about.  Please read carefully my comments below and make the changes as appropriate.__

**[ REQUIRED CHANGES ]**

In this step, you are supposed to only **_mock_** the basic flow of the game. This means implementing a user interface that displays prompt for users (print/puts) and collects user input (`get.chomp`). No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no matter who won. Usage of inline comments in this milestone is allowed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

_Again, you have to write codes to accept the basic inputs and outputs of the game, in order to interact with the player. No serious logic is required here and no condition is checked yet, you just have to code the part of the project that interacts with the player._

**You have to CODE the following features of the game.**
- [x] **Display prompts for users (hint: puts/print)**
- Collect user inputs like player name or player move (hint: get.chomp) and only mock the basic flow of the game 
- After that, you can use puts or inline comments to say for example “Now, your move is displayed on the board”.

- [x]  **Your game should be able to tell which player turn it is.** Again, no winner or loser is determined here. No logic is required yet. Just pick a player at random (either P1 or P2) and print the player as the next to make a move.

- [x] **Your game should be able to ask the player to select from available moves.** 
- In this milestone, you're not processing the move. 
- All you have to do is just code the feature that accepts a move from the player.

- [ ] Your game should be able to display board after the player move (without computing which spots on the board are taken)
- This is another output that interacts with the player. All you have to do here is to display the game board immediately after a player makes a move.

- [ ] **Your game should repeat all actions for the next player's move**
- You can put all the inputs/outputs specified above in a simple while loop. 
- The loop may look like the snippet below:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```


- [ ] **Make sure that you can run your game with your executable file and play with the basic flow.** You should be able to run your game and have a normal interaction with the game.


**[ COMMENTS ]**
- This is just a basic input/output game flow milestone.
- The input part is where your game collects data such as name and moves from the player using `get.chomp`.
- The output part is where you use `puts/print/p` to display information to the player.
- Feel free to reach out to me or the previous TSE on slack if you're in doubt.

* * * 

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-22 21:07 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] I get an error after choosing a place on the board 

![image](https://user-images.githubusercontent.com/11758151/96929801-a92d8900-14b2-11eb-93ca-cf13bc800663.png)


- [x] game should inform the player if the selected move is a draw move (without computing draw)

- [x] check more below 👇 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-10-22 21:07 UTC, SpaYco commented on bin/main.rb
> +# rubocop:disable Lint/RedundantCopDisableDirective
- [x] please don't disable cops, you can most of the time find a way to fix the issues, remove these and fix them.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

2020-10-22 21:07 UTC, SpaYco commented on bin/main.rb
> +  end
- [x] In this step you are supposed to only **mock** the basic flow of the game. This means implementing a user interface that displays prompt for users (print/puts) and collects user input (`get.chomp`). No game logic (for example checking who is a winner) is required in this milestone - instead, students can just display "The winner is X" no mater who won. Usage of inline comments in this milestone is allowed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-10-22 21:07 UTC, SpaYco commented on bin/main.rb
> +    while i < 9 do
- [x] [Optional] try not to use a number to end the loop but instead use a boolean that ends it if a player won or in case of a draw

2020-10-22 23:04 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Let's work on all requirements as stipulated by previous TSE @Spayco 

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-10-23 07:28 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO @alejandrotoledoweb  :wave: NICE PROGRESS SO FAR. GOOD JOB TRYING TO IMPLEMENT THE CHANGES AS REQUESTED BY THE PREVIOUS TSE. THERE JUST A FEW MORE CHANGES TO BE MADE KINDLY CHECK BELOW :arrow_down: 

- [x]  You have committed the .vscode folder, kindly add this folder to the .gitignore.

- [ ]  You have two main files in your bin folder. Kindly there should be only one.

**if you have any question kindly reach me on slach @peterrobert**

### HAPPY CODING :computer:

2020-10-23 07:28 UTC, peterrobert commented on bin/main.rb
> +# rubocop:disable Lint/RedundantCopDisableDirective
You have disabled so many cops. Just as suggested by the previous TSE this should not be the case. Instead of disabling, try and fix the errors

2020-10-23 07:28 UTC, peterrobert commented on bin/main.rb
> +  # rubocop:disable Metrics/CyclomaticComplexity
Kindly fix this. Like suggested above

2020-10-23 20:17 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge  !!!

2020-10-24 14:41 UTC, merged